-- =====================================================================
-- Argus - Supabase schema
-- Base reutilizada desde RadarHuman para entrevista, agentes, mapas vivos
-- y evidencia de busqueda. Ejecutar en el SQL Editor de Supabase.
-- =====================================================================

-- Required extensions
create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";
create extension if not exists "vector";

-- ---------------------------------------------------------------------
-- cases: one row per missing-person report
-- ---------------------------------------------------------------------
create table if not exists cases (
  id              uuid primary key default gen_random_uuid(),
  reporter_phone  text not null,
  reporter_chat_id text not null,
  reporter_name   text,
  status          text not null default 'intake',
    -- intake | portrait | searching | match_found | closed
  description     jsonb not null default '{}'::jsonb,
  portrait_url    text,
  embedding       vector(1024),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists idx_cases_phone   on cases (reporter_phone);
create index if not exists idx_cases_status  on cases (status);
create index if not exists idx_cases_updated on cases (updated_at desc);

-- ---------------------------------------------------------------------
-- conversation_messages: full Agente 0 transcript per case
-- ---------------------------------------------------------------------
create table if not exists conversation_messages (
  id          uuid primary key default gen_random_uuid(),
  case_id     uuid not null references cases(id) on delete cascade,
  role        text not null check (role in ('user','assistant','system','tool')),
  content     text not null,
  media_type  text default 'text',
  created_at  timestamptz not null default now()
);

create index if not exists idx_msgs_case on conversation_messages (case_id, created_at);

-- ---------------------------------------------------------------------
-- media: any image/audio attached to a case (input or generated)
-- ---------------------------------------------------------------------
create table if not exists media (
  id          uuid primary key default gen_random_uuid(),
  case_id     uuid not null references cases(id) on delete cascade,
  kind        text not null,  -- 'input_audio' | 'input_image' | 'portrait' | 'viral_post'
  url         text not null,
  meta        jsonb default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- matches: detecciones producidas por Ghost / agentes de busqueda
-- ---------------------------------------------------------------------
create table if not exists matches (
  id              uuid primary key default gen_random_uuid(),
  case_id         uuid not null references cases(id) on delete cascade,
  source_url      text not null,         -- url where the photo was found
  source_site     text,                  -- e.g. "facebook-clone-1"
  photo_url       text not null,         -- url of the matching photo
  confidence      numeric,               -- 0..1 from the vision model
  reasoning       text,                  -- why the model thinks it's a match
  exif            jsonb default '{}'::jsonb,
  gps_lat         double precision,
  gps_lon         double precision,
  taken_at        timestamptz,
  place_label     text,
  notified        boolean not null default false,
  created_at      timestamptz not null default now()
);

create index if not exists idx_matches_case on matches (case_id, created_at desc);

-- ---------------------------------------------------------------------
-- pipeline_events: granular agent activity for real-time dashboard
-- ---------------------------------------------------------------------
create table if not exists pipeline_events (
  id          uuid primary key default gen_random_uuid(),
  case_id     uuid not null references cases(id) on delete cascade,
  agent       text not null,        -- 'agent0' | 'agent1' | 'agent2' | 'agent3' | 'agent4' | 'pipeline'
  event       text not null,        -- 'start' | 'progress' | 'complete' | 'error'
  payload     jsonb default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

create index if not exists idx_pipeline_events_case on pipeline_events (case_id, created_at desc);

-- Enable realtime for live maps and operational dashboard.
do $$
begin
  begin
    alter publication supabase_realtime add table pipeline_events;
  exception
    when duplicate_object then null;
  end;
end$$;

-- ---------------------------------------------------------------------
-- viral_posts: previews generated by Agente 3 (not actually published)
-- ---------------------------------------------------------------------
create table if not exists viral_posts (
  id          uuid primary key default gen_random_uuid(),
  case_id     uuid not null references cases(id) on delete cascade,
  platform    text not null,             -- whatsapp | facebook | twitter | instagram
  copy        text not null,
  image_url   text,
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Storage buckets (created via SQL - alternative is dashboard UI)
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values
  ('portraits',   'portraits',   true),
  ('viral-posts', 'viral-posts', true),
  ('case-media',  'case-media',  true)
on conflict (id) do nothing;

do $$
begin
  begin
    alter publication supabase_realtime add table cases;
  exception
    when duplicate_object then null;
  end;

  begin
    alter publication supabase_realtime add table matches;
  exception
    when duplicate_object then null;
  end;
end$$;

-- Public read policy for the demo (tighten later for prod)
do $$
begin
  if not exists (
    select 1 from pg_policies where policyname = 'public_read_portraits'
  ) then
    create policy "public_read_portraits"
      on storage.objects for select
      using (bucket_id in ('portraits','viral-posts','case-media'));
  end if;
end$$;
